### ISSUE TITLE
Docs not building correctly on readthedocs

### ISSUE THREAD

**Issue by flowersw** [alexlemann/pipeline#1]
Ex. https://pypipeline.readthedocs.io/en/latest/reference.html

**Comment by flowersw** [comment]
I was able to build the docs locally just fine (though needed to install requirements from both projects, also needed lxml and Sphinx). How were docs built on readthedocs?

**Comment by alexlemann** [comment]
@flowersw I made a couple of changes to the rtd config. Does that help?
What's your username on RTD? I'll add you to the project.

**Comment by flowersw** [comment]
Oh, ok cool. 
I made some improvement here: https://willf-pipeline.readthedocs.io/en/latest/reference.html
Still haven't gotten the examples to show up correctly.

will_flwrs is my RTD name

**Comment by flowersw** [comment]
Not sure why this traceback error is still occuring during the build:
```WARNING: /home/docs/checkouts/readthedocs.org/user_builds/willf-pipeline/checkouts/latest/docs/quickstart.rst:7: (WARNING/2) autodoc: failed to import module 'pipeline.examples.mini'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/willf-pipeline/envs/latest/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
    __import__(self.modname)
ImportError: No module named 'pipeline.examples'
```

**Comment by flowersw** [comment]
Got the examples up: https://willf-pipeline.readthedocs.io/en/latest/quickstart.html
I tried several things, I'll need to pair down exactly what it was

**Comment by flowersw** [comment]
https://github.com/alexlemann/pipeline/compare/master...flowersw:master shows a few file differences, and I made a few tweaks to the config in RTD of my build as well

**Comment by alexlemann** [comment]
@flowersw added you as a maintainer on rtd. And I can merge a PR here if it's ready.

**Comment by alexlemann** [comment]
The build reran and the code examples look good again
http://pypipeline.readthedocs.io/en/latest/quickstart.html
:dart:
